### ISSUE TITLE
Incompatible with maven 3

### ISSUE THREAD

**Issue by btbouwens** [Debian/maven-debian-helper#1]
I'm trying to use this maven-debian-helper but run into lots of problems, starting with its install reverting maven to the old version 2 (nobody uses that anymore, right?).

Then mvn-debian gives me a BUILD ERROR,
Reason: POM 'org.apache.maven.plugins:maven-compiler-plugin' not found in repository: System is offline.

  org.apache.maven.plugins:maven-compiler-plugin:pom:2.3.2

which is rather odd as it is in my local repo, but that's not found.

**Comment by ebourg** [comment]
maven-debian-helper 2.0 now uses Maven 3, you can give it a try. The GitHub mirror was out of sync, I fixed that.

**Comment by btbouwens** [comment]
I'm afraid I have failing tests then:

```
-------------------------------------------------------------------------------
Test set: org.debian.maven.packager.DependenciesSolverTest
-------------------------------------------------------------------------------
Tests run: 7, Failures: 2, Errors: 0, Skipped: 0, Time elapsed: 6.345 sec <<< FAILURE!
testSolveBuildhelperPluginDependencies(org.debian.maven.packager.DependenciesSolverTest)  Time elapsed: 0.423 sec  <<< FAILURE!
junit.framework.ComparisonFailure: File buildhelper-maven-plugin.substvars
different from resource buildhelper-maven-plugin.substvars
expected:
maven.CompileDepends=libmaven-plugin-tools-java
found:
maven.CompileDepends=
 expected:<...aven.CompileDepends=[libmaven-plugin-tools-java]> but was:<...aven.CompileDepends=[]>
        at junit.framework.Assert.assertEquals(Assert.java:100)
        at junit.framework.TestCase.assertEquals(TestCase.java:261)
        at org.debian.maven.packager.DependenciesSolverTest.assertFileEquals(DependenciesSolverTest.java:335)
        at org.debian.maven.packager.DependenciesSolverTest.testSolveBuildhelperPluginDependencies(DependenciesSolverTest.java:253)
        at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at java.lang.reflect.Method.invoke(Method.java:498)
   ...
testSolvePlexusActiveCollectionsDependencies(org.debian.maven.packager.DependenciesSolverTest)  Time elapsed: 0.024 sec  <<< FAILURE!
junit.framework.ComparisonFailure: File libplexus-active-collections-java.substvars
different from resource libplexus-active-collections-java.substvars
expected:
maven.Depends=libplexus-component-api-java, libplexus-containers-java
found:
maven.Depends=libplexus-containers-java
 expected:<...Depends=libplexus-co[mponent-api-java, libplexus-co]ntainers-java> but was:<...Depends=libplexus-co[]ntainers-java>
        at junit.framework.Assert.assertEquals(Assert.java:100)
        at junit.framework.TestCase.assertEquals(TestCase.java:261)
        at org.debian.maven.packager.DependenciesSolverTest.assertFileEquals(DependenciesSolverTest.java:335)
        at org.debian.maven.packager.DependenciesSolverTest.testSolvePlexusActiveCollectionsDependencies(DependenciesSolverTest.java:92)

```

**Comment by ebourg** [comment]
These tests need to be updated, thank you for pointing this out. But this doesn't affect the maven-debian-helper integration with Maven 3.

**Comment by btbouwens** [comment]
OK, so I can skip the tests. Then I ran into some dependency issues, so I couldn't install it.
I installed a new Debian 8u3 box, where I could install this package.
Then:
```
Can't locate object method "doit_in_builddir_noerror" via package "Debian::Debhelper::Buildsystem::maven" at /usr/share/perl5/Debian/Debhelper/Buildsystem/maven.pm line 129.
```
which apparently relates to debhelper being 9.20150101. Quite strange on
Linux linbox 3.16.0-4-amd64 #1 SMP Debian 3.16.7-ckt20-1+deb8u3 (2016-01-17) x86_64 GNU/Linux

**Comment by ebourg** [comment]
maven-debian-helper 2 doesn't work with Debian 8, it'll be part of Debian 9 "Stretch".

What are you trying to do? Maybe there is a better solution to solve your issue.

**Comment by btbouwens** [comment]
The plan was to wrap my Java application, currently just a jar file and a matching .desktop file into a Debian package. For now the jar contains its dependencies, but if all works well I could just let Debian fetch them.

Indeed it would be simpler to just have an install script put the stuff in place, and then it works on Fedora too.

**Comment by ebourg** [comment]
The main purpose of maven-debian-helper is to build .deb packages intended to be distributed by Debian through the official repositories. For third party packages there are easier alternatives like [jdeb](https://github.com/tcurdt/jdeb), it allows you to build Debian packages on any platform unlike maven-debian-helper, and directly from your own build system.

**Comment by btbouwens** [comment]
OK, that's a very helpful comment. Indeed jdeb does what I need, so I won't be needing this plugin.
Thanks - Bram
